FUNC curl_global_init(...)
   RETURN NIL
FUNC curl_easy_init(...)
   RETURN NIL
FUNC curl_easy_setopt(...)
   RETURN NIL
FUNC curl_easy_perform(...)
   RETURN NIL
FUNC curl_easy_getinfo(...)
   RETURN NIL
FUNC curl_easy_cleanup(...)
   RETURN NIL
FUNC curl_global_cleanup(...)
   RETURN NIL
